In [16]:
import numpy as np


In [17]:
A=np.random.rand(4,5)
print(A)


[[0.22328435 0.55727854 0.77090804 0.23210593 0.94567845]
 [0.35266461 0.60432954 0.3451098  0.04433512 0.05771241]
 [0.73198601 0.51736668 0.92790435 0.9601382  0.40820621]
 [0.96763504 0.9213744  0.50172356 0.37889407 0.59385304]]


In [24]:
A=np.random.rand(6,5)
print(A)


print("\n",A[[2,4],[3,4]])

[[0.41579271 0.3901608  0.90830086 0.88191883 0.43589276]
 [0.82680614 0.69981008 0.86476296 0.87013806 0.7987004 ]
 [0.46972494 0.6948627  0.45665927 0.69035703 0.01291278]
 [0.84831865 0.36025327 0.71031279 0.8038905  0.90022349]
 [0.95661955 0.69599222 0.03828877 0.94026571 0.5476212 ]
 [0.03658423 0.05113932 0.31322373 0.67472276 0.35116308]]

 [0.69035703 0.5476212 ]
