In [3]:
import scipy.sparse as sp
import numpy as np

In [4]:
A_dense=np.array([[0,1,0,0],[0,0,0,2],[0,0,3,0],[4,0,0,0]])
print("A: \n",A_dense)


A: 
 [[0 1 0 0]
 [0 0 0 2]
 [0 0 3 0]
 [4 0 0 0]]


In [10]:
# ver pág. 354 libro: Johansson2019-Numerical Python Scientific Computing and Data Science Applications with Numpy, SciPy and Matplotlib.pdf
A_dense=np.array([[0,1,0,0],[0,0,0,2],[0,0,3,0],[4,0,0,0]])
print("A_dense: \n",A_dense)
values=[1,2,3,4]
rows=[0,1,2,3]
cols=[1,3,2,0]
A_sparce=sp.coo_matrix((values,(rows,cols)),shape=[4,4])
print("A_sparce: \n",A_sparce)

A_csr=A_sparce.tocsr()
print("A_csr:\n",A_csr)
print(A_csr.data)
print(A_csr.indices)
print(A_csr.indptr)



A_dense: 
 [[0 1 0 0]
 [0 0 0 2]
 [0 0 3 0]
 [4 0 0 0]]
A_sparce: 
 <COOrdinate sparse matrix of dtype 'int64'
	with 4 stored elements and shape (4, 4)>
  Coords	Values
  (0, 1)	1
  (1, 3)	2
  (2, 2)	3
  (3, 0)	4
A_csr:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (4, 4)>
  Coords	Values
  (0, 1)	1
  (1, 3)	2
  (2, 2)	3
  (3, 0)	4
[1 2 3 4]
[1 3 2 0]
[0 1 2 3 4]


In [ ]:
data=[1,3,2,5,6]
indices=[2,1,3,2,4]
indptr=[0,2,4,5]
B_csr=sp.csr_array((data,indices,indptr),shape=[3,5])
print("B_csr;\n",B_csr)
print(B_csr.toarray())
B_csr.nnz
densidad=

B_csr;
 <Compressed Sparse Row sparse array of dtype 'int64'
	with 5 stored elements and shape (3, 5)>
  Coords	Values
  (0, 2)	1
  (0, 1)	3
  (1, 3)	2
  (1, 2)	5
  (2, 4)	6
[[0 3 1 0 0]
 [0 0 5 2 0]
 [0 0 0 0 6]]


5